# Generated by Django 5.1.3 on 2024-11-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='pet_picture',
            field=models.ImageField(upload_to='adopt-squad/pet-pictures/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='pet_picture',
            field=models.ImageField(upload_to='adopt-squad/pet-pictures/'),
        ),
    ]
