# Generated by Django 5.1.3 on 2024-11-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_cat_pet_picture_alter_dog_pet_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
