# Generated by Django 5.1.3 on 2024-11-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_cat_months_alter_cat_years_alter_dog_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='pet_picture',
            field=models.ImageField(blank=True, null=True, upload_to='adopt-squad/pet-pictures/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='pet_picture',
            field=models.ImageField(blank=True, null=True, upload_to='adopt-squad/pet-pictures/'),
        ),
    ]
