# Generated by Django 5.1.3 on 2024-12-03 18:33

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_cat_pet_picture_alter_dog_pet_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('years', models.PositiveIntegerField(blank=True, null=True)),
                ('months', models.PositiveIntegerField(blank=True, null=True)),
                ('pet_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('personality', models.CharField(choices=[('Playful', 'Playful'), ('Calm', 'Calm'), ('Unsocial', 'Unsocial'), ('Social', 'Social'), ('Energetic', 'Energetic')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='months',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='personality',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='pet_picture',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='years',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='months',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='personality',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='pet_picture',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='years',
        ),
        migrations.AddField(
            model_name='cat',
            name='pet_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.pet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='pet_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.pet'),
            preserve_default=False,
        ),
    ]
