# Generated by Django 5.1.3 on 2024-12-09 20:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_pet_remove_cat_id_remove_cat_months_remove_cat_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_picture',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
