# Generated by Django 5.1.3 on 2024-12-03 18:37

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0006_pet_remove_cat_id_remove_cat_months_remove_cat_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='photo')),
                ('time_of_publication', models.DateTimeField(auto_now_add=True)),
                ('pets', models.ManyToManyField(blank=True, null=True, related_name='photos', to='pets.pet')),
            ],
        ),
    ]
